apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: product-list-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5070
      imagePullSecrets:
        - name: my-secret
