apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment.yaml
images:
  - name: demolearnacr.azurecr.io/demo_dev/product-list-app
    newName: demolearnacr.azurecr.io/demo_dev/product-list-app
    newTag: dev
