apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  #type: NodePort
  selector:
    app.kubernetes.io/name: my-app
  ports:
    - protocol: TCP
      port: 5070
      targetPort: 5070
      # nodePort: 30100
