apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: myapp
          image: demolearnacr.azurecr.io/demo_dev/product-list-app:${{ github.sha }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5070
      imagePullSecrets:
        - name: my-secret

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5070
      targetPort: 5070
