name: 'Build and Push '

on:
  push:
    branches: 
      - 'main'
  

permissions:
  id-token: write
  contents: read
  
jobs:
  Docker:
    name: 'Docker'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4	
    - name: Azure Login
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

    - name: Login to Azure Container Registry
      run: az acr login --name demolearnacr
    - name: build image
      run: docker build -t demolearnacr.azurecr.io/demo_dev/product_list_app:${{ github.sha }} .
      working-directory: ./src
    - name : push image to acr
      run: docker push demolearnacr.azurecr.io/demo_dev/product_list_app:${{ github.sha }}
    - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifest/deployment.yml'
        propertyPath: 'spec.template.spec.containers.0.image'
        value: demolearnacr.azurecr.io/demo_dev/product-list-app:${{ github.sha }}
        token: ${{ secrets.ACCESS_TOKEN }}        
        commitChange: true
        createPR: false
        branch: main